# -*- coding: utf-8 -*-
"""Data Analyst_Kel_Traveloka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157ExVgQydwSRd73ZGh_qNU8ovHjtlavO
"""

!pip install openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid", rc={"grid.alpha": 0.15})
plt.rcParams['figure.figsize'] = (12, 6.5)
plt.rcParams['font.family'] = 'sans-serif'

t_blue = '#0194E1'
t_dark = '#0B3960'
t_orange = '#FF5E1F'
t_pastel_blue = '#E6F4FD'
traveloka_palette = [t_blue, '#4DB4E9', '#92D3F2', '#D7F1FC', '#F0FAFE']

file_excel = '/content/data_traveloka_200_playstore.xlsx'
df_kuesioner = pd.read_excel(file_excel, sheet_name='Data_Kuesioner_Form')
df_playstore = pd.read_excel(file_excel, sheet_name='Data_Playstore_200')

print("=== [SUKSES] SEMUA DATA BERHASIL DIMUAT ===")
print("Data Kuesioner (GForm):", df_kuesioner.shape)
print("Data Play Store (Scraping):", df_playstore.shape)

kolom_gender = [col for col in df_kuesioner.columns if 'kelamin' in col.lower() or 'gender' in col.lower()]

if kolom_gender:
    data_gender = df_kuesioner[kolom_gender[0]].value_counts()

    labels_gender_legenda = [f'{idx} ({val} Orang, {val/sum(data_gender)*100:.1f}%)' for idx, val in zip(data_gender.index, data_gender.values)]

    plt.figure(figsize=(8, 6))

    patches, texts, autotexts = plt.pie(
        data_gender,
        labels=None,
        autopct='%1.1f%%',
        startangle=90,
        colors=['#48DBFB', '#FF6B6B'],
        wedgeprops={'edgecolor': 'white', 'linewidth': 3, 'antialiased': True},
        pctdistance=0.7
    )

    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_fontweight('bold')
        autotext.set_fontsize(12)

    centre_circle = plt.Circle((0,0), 0.50, fc='white')
    fig = plt.gcf()
    fig.gca().add_artist(centre_circle)

    plt.legend(
        patches,
        labels_gender_legenda,
        title="jenis kelamin",
        title_fontsize=11,
        loc="upper center",
        bbox_to_anchor=(0.5, -0.05),
        ncol=2,
        frameon=True,
        facecolor='#F8F9FA',
        edgecolor='none',
        fontsize=10
    )

    plt.title('Profil Responden Kuesioner Berdasarkan Jenis Kelamin', fontsize=14, fontweight='bold', color=t_dark, pad=25)
    plt.tight_layout()
    plt.show()

else:
    print("[Info] Kolom bertema 'Jenis Kelamin' atau 'Gender' tidak ditemukan di data kuesioner kamu.")

data_usia = df_kuesioner['Usia '].value_counts()

labels_legenda = [f'{idx} ({val} Orang, {val/sum(data_usia)*100:.1f}%)' for idx, val in zip(data_usia.index, data_usia.values)]

plt.figure(figsize=(11, 7))

patches, texts, autotexts = plt.pie(
    data_usia,
    labels=None,
    autopct='%1.1f%%',
    startangle=140,
    colors=['#54A0FF', '#5F27CD', '#FF6B6B', '#FFED4A', '#48DBFB'],
    wedgeprops={'edgecolor': 'white', 'linewidth': 3, 'antialiased': True},
    pctdistance=0.75
)

for autotext in autotexts:
    autotext.set_color('white')
    autotext.set_fontweight('bold')
    autotext.set_fontsize(11)

centre_circle = plt.Circle((0,0), 0.55, fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)

plt.legend(
    patches,
    labels_legenda,
    title="Kelompok Usia Responden",
    loc="center left",
    bbox_to_anchor=(1, 0, 0.5, 1),
    frameon=True,
    facecolor='#F8F9FA',
    edgecolor='none',
    fontsize=10
)

plt.title('Profil Responden Kuesioner Berdasarkan Kelompok Usia', fontsize=14, fontweight='bold', color=t_dark, pad=25)
plt.tight_layout()
plt.show()

"""# Rata-rata Skor Kepuasan Aspek Utama Aplikasi di Kuesioner"""

fitur_utama = df_kuesioner.iloc[:, [5, 6, 7, 8]]
rata_rata_skor = fitur_utama.mean()

nama_singkat = [
    'Kemudahan Pencarian\n& Sistem Pembayaran',
    'Daya Tarik Estetika\nAntarmuka (UI) Aplikasi',
    'Kecepatan Respon\n& Performa Aplikasi',
    'Stabilitas Sistem\n(Aplikasi Bebas Bug)'
]

plt.figure(figsize=(11, 5.5))
bars = plt.barh(nama_singkat, rata_rata_skor.values, color=t_blue, height=0.5, edgecolor='none')

for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.08, bar.get_y() + bar.get_height()/2, f'{width:.2f} / 5.0',
             va='center', ha='left', fontweight='bold', color=t_dark, fontsize=10)

plt.title('Rata-rata Skor Kepuasan Aspek Utama Aplikasi di Kuesioner', fontsize=14, fontweight='bold', color=t_dark, pad=25)
plt.xlabel('Skala Penilaian Mean (1.0 - 5.0)', fontsize=11, fontweight='bold', labelpad=12)
plt.xlim(0, 5.7)
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""# Analisis Pengaruh Fitur PayLater terhadap Keputusan Transaksi Berdasarkan Usia di Kuesioner"""

kolom_paylater = [col for col in df_kuesioner.columns if 'PayLater' in col or 'paylater' in col.lower()][0]
ct = pd.crosstab(df_kuesioner['Usia '], df_kuesioner[kolom_paylater], normalize='index') * 100

ax = ct.plot(kind='bar', stacked=True, cmap='Spectral', edgecolor='white', width=0.5, figsize=(13, 6.5))

plt.title('Analisis Pengaruh Fitur PayLater terhadap Keputusan Transaksi Berdasarkan Usia di Kuesioner', fontsize=14, fontweight='bold', color=t_dark, pad=25)
plt.xlabel('Kelompok Usia Responden', fontsize=11, fontweight='bold', labelpad=15)
plt.ylabel('Persentase Pilihan (%)', fontsize=11, fontweight='bold')

plt.xticks(rotation=15, ha='right', fontsize=9.5)
plt.yticks(fontsize=10)

plt.legend(title='Skala Penilaian', bbox_to_anchor=(1.02, 1), loc='upper left', frameon=True, facecolor='white', edgecolor='none')
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""# Kategori Keluhan Terbesar Penyebab Rating Buruk (Bintang 1 & 2) di Play Store"""

df_rating_rendah = df_playstore[df_playstore['rating'].isin([1, 2])]
order_keluhan = df_rating_rendah['kategori keluhan'].value_counts().index

plt.figure(figsize=(11, 6))
sns.countplot(
    data=df_rating_rendah,
    y='kategori keluhan',
    order=order_keluhan,
    palette=sns.light_palette(t_orange, reverse=True, n_colors=len(order_keluhan))
)

plt.title('Kategori Keluhan Terbesar Penyebab Rating Buruk (Bintang 1 & 2) di Play Store', fontsize=14, fontweight='bold', color=t_dark, pad=25)
plt.xlabel('Jumlah Keluhan yang Teridentifikasi', fontsize=11, fontweight='bold', labelpad=12)
plt.ylabel('Kategori Kendala Pengguna', fontsize=11, fontweight='bold')
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""# Komposisi Persebaran Rating Bintang (1 - 5) pada Tiap Kategori Keluhan di Play Stor"""

pivot_rating_keluhan = pd.crosstab(df_playstore['kategori keluhan'], df_playstore['rating'])

pivot_rating_keluhan['Total'] = pivot_rating_keluhan.sum(axis=1)
pivot_rating_keluhan = pivot_rating_keluhan.sort_values(by='Total', ascending=False).drop(columns='Total')

ax = pivot_rating_keluhan.plot(kind='bar', figsize=(13, 6.5), width=0.8, color=traveloka_palette, edgecolor='none')

plt.title('Komposisi Persebaran Rating Bintang (1 - 5) pada Tiap Kategori Keluhan di Play Store', fontsize=14, fontweight='bold', color=t_dark, pad=25)
plt.xlabel('Kategori Keluhan di Play Store', fontsize=11, fontweight='bold', labelpad=15)
plt.ylabel('Jumlah Ulasan Pengguna', fontsize=11, fontweight='bold')

plt.xticks(rotation=20, ha='right', fontsize=9.5)
plt.legend(title='Rating Bintang', loc='upper right', frameon=True, facecolor='white')
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""# Tren Fluktuasi Jumlah Masuknya Ulasan Pengguna Traveloka per Hari di Play Store"""

df_playstore['tanggal_clean'] = pd.to_datetime(df_playstore['tanggal']).dt.date
tren_harian = df_playstore['tanggal_clean'].value_counts().sort_index()

plt.figure(figsize=(12, 5.5))
plt.plot(tren_harian.index, tren_harian.values, color=t_orange, marker='o', linewidth=2.5, markersize=6, markerfacecolor='white', markeredgewidth=2)

plt.title('Tren Fluktuasi Jumlah Masuknya Ulasan Pengguna Traveloka per Hari di Play Store', fontsize=14, fontweight='bold', color=t_dark, pad=25)
plt.xlabel('Garis Waktu / Tanggal Ulasan', fontsize=11, fontweight='bold', labelpad=12)
plt.ylabel('Total Ulasan Masuk', fontsize=11, fontweight='bold')
plt.xticks(rotation=15, ha='right', fontsize=9.5)
plt.tight_layout()
plt.show()